---
abstract: "Perl extension for talking 37Signals' Highrise API"
author:
  - 'Danny Sadinoff <danny@sadinoff.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200013, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-ThirtySevenSignals-Highrise
requires:
  HTTP::Request: 0
  LWP::UserAgent: 0
  Log::Log4perl: 0
  Test::More: 0
  URI: 0
  XML::Simple: 0
version: 0.03
